# app.yaml
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^node_modules/(.*/)?
- ^gulpfile\.js
- ^package\.json


handlers:
- url: /static
  static_dir: static
- url: /basedata/v1/.*
  script: main.app

# ssl is needed 
libraries:
- name: ssl
  version: latest